
pipeline {
  agent {
        docker {
            image 'node:16-alpine' // Specify the Docker image you want to use
            args '-v /var/run/docker.sock:/var/run/docker.sock' 
        }
  }


  stages {

    stage("install dependencies") {

      steps {

        sh 'npm install'

      }

    }
    stage("Test") {

      steps {

        sh 'npm run  test:unit'

      }

    }

    stage("Build") {

      steps {

        sh 'npm run build'
      }

    }

}
}